--- 
console_eventlog_verbosity: error
console_mouse: false
console_palette: dark
scripts: 
  - ~/.mitmproxy/scripts/toggle_system_proxies.py
  - ~/.mitmproxy/scripts/error_response.py
view_filter: "~dst amazon.com|google.com"
